package com.sys.common.model;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {
	
	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("t_module", "id", Module.class);
		arp.addMapping("t_permission", "id", Permission.class);
		arp.addMapping("t_role", "id", Role.class);
		arp.addMapping("t_user", "id", User.class);
		arp.addMapping("t_user_role", "id", UserRole.class);
	}
}

