package com.sys.common.model;

import com.sys.common.model.base.BaseModule;

import java.util.ArrayList;
import java.util.List;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Module extends BaseModule<Module> {

    private Integer pId;
    private String name;
    private Boolean checked=false;

    /**
     *  主页菜单展示属性扩展
     */
    private String icon;
    private String href;
    private Boolean spread;
    private List<Module> children = new ArrayList<Module>();

    public String getIcon() {
        return getStr("icon");
    }

    public void setIcon(String icon) {
        super.put("icon",icon);
    }

    public String getHref() {
        return getStr("");
    }

    public void setHref(String href) {
        super.put("href",href);
    }

    public Boolean getSpread() {
        return getBoolean("spread");
    }

    public void setSpread(Boolean spread) {
        super.put("spread",spread);
    }

    public List<Module> getChildren() {
        return  get("children");
    }

    public void setChildren(List<Module> children) {
        super.put("children",children);
    }




    public Boolean getChecked() {
        return getBoolean("checked");
    }

    public void setChecked(Boolean checked) {
        super.put("checked",checked);
    }

    public Integer getpId() {
        return pId;
    }

    public void setpId(Integer pId) {
        this.pId = pId;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }
}
