package com.sys.common.model;

import com.sys.common.model.base.BaseUser;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class User extends BaseUser<User> {

    private String roleIds;

    public void setRoleIds(String roleIds) {
        this.roleIds = roleIds;
    }

    public String getRoleIds() {
        return roleIds;
    }
}
