package com.lbt.common.model;

import com.jfinal.plugin.activerecord.Model;
import lombok.Data;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
@Data
public class User extends Model<User> {
    private String userName;
    private String userPwd;
    private String trueName;
    private String abc;
}
