package com.sys.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseRole<M extends BaseRole<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public void setRoleName(java.lang.String roleName) {
		set("roleName", roleName);
	}
	
	public java.lang.String getRoleName() {
		return getStr("roleName");
	}

	/**
	 * 备注
	 */
	public void setRoleRemark(java.lang.String roleRemark) {
		set("roleRemark", roleRemark);
	}
	
	/**
	 * 备注
	 */
	public java.lang.String getRoleRemark() {
		return getStr("roleRemark");
	}

	public void setCreateDate(java.util.Date createDate) {
		set("createDate", createDate);
	}
	
	public java.util.Date getCreateDate() {
		return get("createDate");
	}

	public void setUpdateDate(java.util.Date updateDate) {
		set("updateDate", updateDate);
	}
	
	public java.util.Date getUpdateDate() {
		return get("updateDate");
	}

	public void setIsValid(java.lang.Integer isValid) {
		set("isValid", isValid);
	}
	
	public java.lang.Integer getIsValid() {
		return getInt("isValid");
	}

}
