package com.sys.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseUser<M extends BaseUser<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public void setUserName(java.lang.String userName) {
		set("userName", userName);
	}
	
	public java.lang.String getUserName() {
		return getStr("userName");
	}

	public void setUserPwd(java.lang.String userPwd) {
		set("userPwd", userPwd);
	}
	
	public java.lang.String getUserPwd() {
		return getStr("userPwd");
	}

	public void setTrueName(java.lang.String trueName) {
		set("trueName", trueName);
	}
	
	public java.lang.String getTrueName() {
		return getStr("trueName");
	}

	public void setEmail(java.lang.String email) {
		set("email", email);
	}
	
	public java.lang.String getEmail() {
		return getStr("email");
	}

	public void setPhone(java.lang.String phone) {
		set("phone", phone);
	}
	
	public java.lang.String getPhone() {
		return getStr("phone");
	}

	public void setIsValid(java.lang.Integer isValid) {
		set("isValid", isValid);
	}
	
	public java.lang.Integer getIsValid() {
		return getInt("isValid");
	}

	public void setCreateDate(java.util.Date createDate) {
		set("createDate", createDate);
	}
	
	public java.util.Date getCreateDate() {
		return get("createDate");
	}

	public void setUpdateDate(java.util.Date updateDate) {
		set("updateDate", updateDate);
	}
	
	public java.util.Date getUpdateDate() {
		return get("updateDate");
	}

	public void setIsDel(java.lang.Integer isDel) {
		set("isDel", isDel);
	}
	
	public java.lang.Integer getIsDel() {
		return getInt("isDel");
	}

}
