package com.sys.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseModule<M extends BaseModule<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	/**
	 * 资源名称
	 */
	public void setModuleName(java.lang.String moduleName) {
		set("moduleName", moduleName);
	}
	
	/**
	 * 资源名称
	 */
	public java.lang.String getModuleName() {
		return getStr("moduleName");
	}

	/**
	 * 模块样式
	 */
	public void setModuleStyle(java.lang.String moduleStyle) {
		set("moduleStyle", moduleStyle);
	}
	
	/**
	 * 模块样式
	 */
	public java.lang.String getModuleStyle() {
		return getStr("moduleStyle");
	}

	/**
	 * 地址
	 */
	public void setUrl(java.lang.String url) {
		set("url", url);
	}
	
	/**
	 * 地址
	 */
	public java.lang.String getUrl() {
		return getStr("url");
	}

	public void setParentId(java.lang.Integer parentId) {
		set("parentId", parentId);
	}
	
	public java.lang.Integer getParentId() {
		return getInt("parentId");
	}

	public void setParentOptValue(java.lang.String parentOptValue) {
		set("parentOptValue", parentOptValue);
	}
	
	public java.lang.String getParentOptValue() {
		return getStr("parentOptValue");
	}

	/**
	 * 等级
	 */
	public void setGrade(java.lang.Integer grade) {
		set("grade", grade);
	}
	
	/**
	 * 等级
	 */
	public java.lang.Integer getGrade() {
		return getInt("grade");
	}

	/**
	 * 权限值
	 */
	public void setOptValue(java.lang.String optValue) {
		set("optValue", optValue);
	}
	
	/**
	 * 权限值
	 */
	public java.lang.String getOptValue() {
		return getStr("optValue");
	}

	public void setOrders(java.lang.Integer orders) {
		set("orders", orders);
	}
	
	public java.lang.Integer getOrders() {
		return getInt("orders");
	}

	public void setIsValid(java.lang.Integer isValid) {
		set("isValid", isValid);
	}
	
	public java.lang.Integer getIsValid() {
		return getInt("isValid");
	}

	public void setCreateDate(java.util.Date createDate) {
		set("createDate", createDate);
	}
	
	public java.util.Date getCreateDate() {
		return get("createDate");
	}

	public void setUpdateDate(java.util.Date updateDate) {
		set("updateDate", updateDate);
	}
	
	public java.util.Date getUpdateDate() {
		return get("updateDate");
	}

}
