package com.lbt.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseRole<M extends BaseRole<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public void setRoleName(java.lang.String roleName) {
		set("role_name", roleName);
	}
	
	public java.lang.String getRoleName() {
		return getStr("role_name");
	}

	/**
	 * 备注
	 */
	public void setRoleRemark(java.lang.String roleRemark) {
		set("role_remark", roleRemark);
	}
	
	/**
	 * 备注
	 */
	public java.lang.String getRoleRemark() {
		return getStr("role_remark");
	}

	public void setCreateDate(java.util.Date createDate) {
		set("create_date", createDate);
	}
	
	public java.util.Date getCreateDate() {
		return get("create_date");
	}

	public void setUpdateDate(java.util.Date updateDate) {
		set("update_date", updateDate);
	}
	
	public java.util.Date getUpdateDate() {
		return get("update_date");
	}

	public void setIsValid(java.lang.Integer isValid) {
		set("is_valid", isValid);
	}
	
	public java.lang.Integer getIsValid() {
		return getInt("is_valid");
	}

}
