package com.lbt.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseModule<M extends BaseModule<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	/**
	 * 资源名称
	 */
	public void setModuleName(java.lang.String moduleName) {
		set("module_name", moduleName);
	}
	
	/**
	 * 资源名称
	 */
	public java.lang.String getModuleName() {
		return getStr("module_name");
	}

	/**
	 * 模块样式
	 */
	public void setModuleStyle(java.lang.String moduleStyle) {
		set("module_style", moduleStyle);
	}
	
	/**
	 * 模块样式
	 */
	public java.lang.String getModuleStyle() {
		return getStr("module_style");
	}

	/**
	 * 地址
	 */
	public void setUrl(java.lang.String url) {
		set("url", url);
	}
	
	/**
	 * 地址
	 */
	public java.lang.String getUrl() {
		return getStr("url");
	}

	public void setParentId(java.lang.Integer parentId) {
		set("parent_id", parentId);
	}
	
	public java.lang.Integer getParentId() {
		return getInt("parent_id");
	}

	public void setParentOptValue(java.lang.String parentOptValue) {
		set("parent_opt_value", parentOptValue);
	}
	
	public java.lang.String getParentOptValue() {
		return getStr("parent_opt_value");
	}

	/**
	 * 等级
	 */
	public void setGrade(java.lang.Integer grade) {
		set("grade", grade);
	}
	
	/**
	 * 等级
	 */
	public java.lang.Integer getGrade() {
		return getInt("grade");
	}

	/**
	 * 权限值
	 */
	public void setOptValue(java.lang.String optValue) {
		set("opt_value", optValue);
	}
	
	/**
	 * 权限值
	 */
	public java.lang.String getOptValue() {
		return getStr("opt_value");
	}

	public void setOrders(java.lang.Integer orders) {
		set("orders", orders);
	}
	
	public java.lang.Integer getOrders() {
		return getInt("orders");
	}

	public void setIsValid(java.lang.Integer isValid) {
		set("is_valid", isValid);
	}
	
	public java.lang.Integer getIsValid() {
		return getInt("is_valid");
	}

	public void setCreateDate(java.util.Date createDate) {
		set("create_date", createDate);
	}
	
	public java.util.Date getCreateDate() {
		return get("create_date");
	}

	public void setUpdateDate(java.util.Date updateDate) {
		set("update_date", updateDate);
	}
	
	public java.util.Date getUpdateDate() {
		return get("update_date");
	}

}
